### ISSUE TITLE
Mktorrent v1.1 not showing progress status while creating torrent

### ISSUE THREAD

**Issue by Whisper40** [Rudde/mktorrent#57]
Hello !
I was using mktorrent v1.0 that was showing the progress output like that : "1500 pieces of 2000 hashed".
Now i installed rutorrent 3.10, with mktorrent v1.1 and it seems that your tool is not anymore showing the progress of his job.

I think that it is really necessary to know the progress even more with large torrent.

You can see that the issue is really old and has been reported on rutorrent side, but the problem is on mktorrent side..

https://github.com/Novik/ruTorrent/issues/1658

Thanks !

**Comment by pobrn** [comment]
Can you try running `mktorrent` manually? I cannot reproduce the issue locally, it shows the progress. I looked at the differences between 1.0 and 1.1, and I cannot see any change that is related.

**Comment by Whisper40** [comment]
We found that the problem was only on one torrent on our side.. sry !

**Comment by ejadams13** [comment]
i am having this same issue with v1.1 on all torrents (rutorrent v3.10)
