### ISSUE TITLE
Out of memory?

### ISSUE THREAD

**Issue by LaMpiR** [Rudde/mktorrent#6]
I keep getting this error. I tried it so:
mktorrent -a tracker  -p folder-of-file
and I keep getting error out of memory. I did only make and then sudo make PREFIX=/usr install

Linux version 2.6.18-238.9.1.el5.028stab089.1 (root@rhel5-build-x64) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-46)) #1 SMP Thu Apr 14 14:06:01 MSD 2011

**Comment by nikswap** [comment]
what is the size of file/folder?

**Comment by LaMpiR** [comment]
29.43 GB.
